### ISSUE TITLE
Pokemon (Shellder) list id: 090  does not display proper name and type.

### ISSUE THREAD

**Issue by PtrHtn** [shadforth/vue-pokedex#10]
After selecting _Shellder_ pokemon ID: 090 from the list of pokemons on the right side of the page, name and type displayed in the pokemon details section on the left side of the page is not as expected.

![image](https://user-images.githubusercontent.com/24513310/91874283-67b9f380-ec50-11ea-8ed5-f2df36862897.png)

Same issue with: 
- pokemon ID: 139 Omastar
- pokemon ID: 187 Hoppip
- pokemon ID: 222 Corsola

#### _Here you can find automated UI test for this issue_: <https://github.com/PtrHtn/vue-pokedex-ui-test-automation>

**Comment by shadforth** [comment]
Amazing, thank you @PtrHtn! Great test automation project.

**Comment by shadforth** [comment]
Added missing sprites and data.

https://github.com/shadforth/vue-pokedex/commit/027a1f3a007d5d315b21d64fe0462329e3460a00
